language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-111
    - python: 3.6
      env: TOXENV=py36-200
    - python: 3.6
      env: TOXENV=py36-210

before_install:
  - sudo pip install tox
script:
  - tox -e $TOXENV